rr = read.table('ratios.100')
dd = as.dist(1 - cor(t(rr)))
library(fastcluster)
hc=hclust(dd,'average')
#hcb=hclust_bootstrap(dd,3,'average')
library(pvclust)
pvc=pvclust(rr,method.hclust='ward')
plot(pvc)
pvrect(pvc)
